// Questions


export const intermediate = [
  {question: "no me visitó el domingo sino el lunes ", answer: "Did not visit me on sunday but on monday"},
{question: "estoy buscando un regalo para mi madre ", answer: "I'm looking for a gift for my mother"},
{question: "es como buscar una aguja en un pajar ", answer: "It's like looking for a needle in a haystack"},
{question: "no podría haberlo hecho sin ti gracias ", answer: "I couldn't have done it without you thank you"},
{question: "no puedo decirte cómo pronunciar la palabra ", answer: "I can't tell you how to pronounce the word"},
{question: "duerme durante el día y trabaja por la noche", answer: "He sleeps during the day and works at night"},
{question: "nadie entendía por qué el elefante de repente se volvió contra su dueño ", answer: "No one understood why the elephant suddenly turned on its owner"},
{question: "visito su ciudad natal por primera vez en 10 años", answer: "Visited his hometown for the first time in 10 years"},
{question: "a qué distancia está el aeropuerto del hotel ", answer: "How far the airport is from the hotel"},
{question: "qué tan grande es la población de la ciudad de nueva york ", answer: "How big is the population of new york city?"},
{question: "dame la oportunidad de hacer que te sientas orgulloso de mí ", answer: "Give me a chance to make you proud of me"},
{question: "no hace más que quejarse desde la mañana hasta la noche ", answer: "He does nothing but complain from morning till night"},
{question: "mi hijo es ahora tan alto como yo", answer: "My son is now as tall as me"},
{question: "quiero cortarme el pelo antes del viaje ", answer: "I want to get my hair cut before the trip"},
{question: "has trabajado duro durante meses y ciertamente te has ganado unas vacaciones", answer: "You've worked hard for months and you've certainly earned a vacation"},
{question: "va a ser médico cuando crezca ", answer: "He's going to be a doctor when he grows up"},
{question: "la amo tanto que no pudo dejarla", answer: "I love her so much I couldn't leave her"},
{question: "este lugar tiene una atmósfera misteriosa ", answer: "This place has a mysterious atmosphere"},
{question: "los científicos pueden calcular fácilmente la distancia entre planetas ", answer: "Scientists can easily calculate the distance between planets."},
{question: "el ébola se propaga de persona a persona a través de los fluidos corporales", answer: "Ebola spreads from person to person through bodily fluids."},
{question: "el hombre sentado a mi lado me hablo ", answer: "The man sitting next to me spoke to me"},
{question: "después de un par de tragos el tipo no sentía dolor", answer: "After a couple of drinks the guy was feeling no pain"},
{question: "no tenía palabras para expresar sus sentimientos", answer: "He had no words to express his feelings"},
{question: "espero que pueda venir me gustaría verlo", answer: "I hope you can come I'd like to see you"},
{question: "por casualidad me encontré con mi viejo amigo en el aeropuerto", answer: "By chance I ran into my old friend at the airport"},
{question: "he estado viviendo en canadá por 5 años ", answer: "I have been living in canada for 5 years"},
{question: "es bueno leer buenos libros cuando se es joven ", answer: "It's good to read good books when you are young"},
{question: "no quiero involucrarme en ese asunto", answer: "I don't want to get involved in that matter"},
{question: "te imaginas cómo será el siglo 21", answer: "Can you imagine what the 21st century will be like"},
{question: "los plásticos han sustituido a muchos materiales convencionales", answer: "Plastics have replaced a lot of conventional materials"},
{question: "nos llevó media hora montar la tienda", answer: "It took us half an hour to set up the tent"},
{question: "voy a la oficina en bicicleta excepto en días de lluvia ", answer: "I ride my bike to the office except on rainy days."},
{question: "la escuela está a 5 kilómetros de mi casa", answer: "The school is 5 kilometers from my house"},
{question: "me gustaría dejar esta ciudad y no volver nunca más", answer: "I would like to leave this city and never come back."},
{question: "le dará su foto a quien la quiera", answer: "Will give her picture to whoever wants it"},
{question: "y la bandera roja indicaba la presencia de peligro", answer: "The red flag indicated the presence of danger"},
{question: "china es 25 veces más grande que japón", answer: "China is 25 times bigger than japan"},
{question: "la maestra alineó a los niños en orden de altura", answer: "The teacher lined the children up in order of height"},
{question: "no tenías que haberse llevado un paraguas contigo ", answer: "You shouldn't have taken an umbrella with you"},
{question: "me gusta nadar pero no me gusta nadar aquí", answer: "I like to swim but I don't like to swim here"},
{question: "te he estado esperando desde las 2 en punto ", answer: "I've been waiting for you since 2 o'clock"},
{question: "esta guía puede serle útil en su viaje", answer: "This guide may be useful to you on your trip"},
{question: "todo indica que está mejorando ", answer: "All indications are that you are improving"},
{question: "era demasiado baja para ver por encima de la valla ", answer: "She was too short to see over the fence."},
{question: "no es tan inteligente como su hermano", answer: "She's not as smart as her brother"},
{question: "entre tú y yo creo que nuestro jefe es estúpido", answer: "Between you and me I think our boss is stupid"},
{question: "me gustaría vivir en los suburbios de kobe", answer: "I would like to live in the suburbs of kobe"},
{question: "podría explicarme el significado de esta frase", answer: "Could you explain to me the meaning of this sentence"},
{question: "no es fácil aprender un idioma extranjero", answer: "It is not easy to learn a foreign language"},
{question: "la pasaste bien en tu viaje a londres", answer: "You had a good time on your trip to london"},
{question: "la policía cree que el ladrón entró por una ventana del sótano", answer: "The police think the burglar broke in through a basement window"},
{question: "era más hermosa que todas las demás", answer: "She was more beautiful than all the others"},
{question: "la fluidez en el inglés es una habilidad muy comercializable hoy en día", answer: "Fluency in english is a very marketable skill these days"},
{question: "di por sentado que mantendría su palabra ", answer: "I took it for granted that he would keep his word"},
{question: "su ausencia dio lugar a todo tipo de rumores", answer: "His absence gave rise to all sorts of rumors"},
{question: "me pregunto si tienes algo con que escribir ", answer: "I wonder if you have anything to write with"},
{question: "no veo ninguna razón por la que tenga que disculparme ", answer: "I don't see any reason for me to apologize."},
{question: "damos por sentado que tendrá éxito en su negocio", answer: "We take it for granted that you will succeed in your business"},
{question: "no tiene sentido fingir estar enfermo", answer: "There's no point in pretending to be ill"},
{question: "ha pasado mucho tiempo desde la última vez que nos vimos", answer: "It's been a long time since we last saw each other."},
{question: "siempre me baño antes de acostarme", answer: "I always take a bath before going to bed"},
{question: "siempre planea las cosas cuidadosamente antes de hacerlo", answer: "Always plan things carefully before doing them"},
{question: "estaba a punto de ir a buscarte", answer: "I was about to go looking for you"},
{question: "un médico me dijo que comer huevos era malo para mí ", answer: "A doctor told me that eating eggs was bad for me"},
{question: "regreso a casa por primera vez en diez anos", answer: "I'm back home for the first time in ten years."},
{question: "dejar algo sin terminar es lo peor que puedes hacer ", answer: "Leaving something unfinished is the worst thing you can do"},
{question: "odio cuando otra gente me hace esperar mucho tiempo", answer: "I hate it when other people make me wait too long"},
{question: " le proporcionará toda la información necesaria", answer: "Will provide you with all the necessary information"},
{question: "terminar el informe para mañana es casi imposible", answer: "Finishing the report by tomorrow is almost impossible"},
{question: "se lo agradezco de todo corazón", answer: "I thank you from the bottom of my heart"},
{question: "y mi habitación es tres veces más grande que la tuya", answer: "And my room is three times bigger than yours"},
{question: "está bien tomar fotos en este edificio", answer: "It's okay to take pictures in this building"},
{question: "su madre se sentó toda la noche esperando a su hijo ", answer: "His mother sat up all night waiting for her son"},
{question: "lo conozco por su nombre pero no por su vista", answer: "I know him by name but not by sight."},
{question: "compro 6 yardas de tela para un vestido", answer: "I buy 6 yards of fabric for a dress"},
{question: "cicatriz", answer: "cicatriz"},
{question: "me dan ganas de", answer: "makes me want to"},
{question: "un reino marinero", answer: "a sea kingdom"},
{question: "que decepcion", answer: "what a disappointment"}
];

export const alphabet = [
  {question: "A", answer: "ah"},
  {question: "B", answer: "be"},
  {question: "C", answer: "ce"},
  {question: "CH", answer: "che"},
  {question: "D", answer: "de"},
  {question: "E", answer: "eh"},
  {question: "F", answer: "efe"},
  {question: "G", answer: "he"},
  {question: "H", answer: "ache"},
  {question: "I", answer: "e"},
  {question: "J", answer: "jota"},
  {question: "K", answer: "ka"},
  {question: "L", answer: "ele"},
  {question: "LL", answer: "elle"},
  {question: "M", answer: "eme"},
  {question: "N", answer: "ene"},
  {question: "Ñ", answer: "eñe"},
  {question: "O", answer: "oh"},
  {question: "P", answer: "pe"},
  {question: "Q", answer: "cu"},
  {question: "R", answer: "ere"},
  {question: "RR", answer: "erre"},
  {question: "S", answer: "ese"},
  {question: "T", answer: "te"},
  {question: "U", answer: "oo"},
  {question: "V", answer: "uve"},
  {question: "W", answer: "doble oo"},
  {question: "X", answer: "equis"},
  {question: "Y", answer: "i griega"},
  {question: "Z", answer: "zeta "}
];

export const numbers = [
  {question: "1", answer: "uno"},
  {question: "2", answer: "dos"},
  {question: "3", answer: "tres"},
  {question: "4", answer: "cuatro"},
  {question: "5", answer: "cinco"},
  {question: "6", answer: "seis"},
  {question: "7", answer: "siete"},
  {question: "8", answer: "ocho"},
  {question: "9", answer: "nueve"},
  {question: "10", answer: "diez"},
  {question: "11", answer: "once"},
  {question: "12", answer: "doce"},
  {question: "13", answer: "trece"},
  {question: "14", answer: "catorce"},
  {question: "15", answer: "quince"},
  {question: "16", answer: "dieciséis"},
  {question: "17", answer: "diecisiete"},
  {question: "18", answer: "dieciocho"},
  {question: "19", answer: "diecinueve"},
  {question: "20", answer: "veinte"},
  {question: "30", answer: "treinta"},
  {question: "40", answer: "cuarenta"},
  {question: "50", answer: "cincuenta"},
  {question: "60", answer: "sesenta"},
  {question: "70", answer: "setenta"},
  {question: "80", answer: "ochenta"},
  {question: "90", answer: "noventa"},
  {question: "100", answer: "cien"},
  {question: "1000", answer: "mil"},
  {question: "2000", answer: "dos mil"},
  {question: "3000", answer: "tres mil"},
  {question: "4000", answer: "cuatro mil"},
  {question: "5000", answer: "cinco mil"},
  {question: "6000", answer: "seis mil"},
  {question: "7000", answer: "siete mil"},
  {question: "8000", answer: "ocho mil"},
  {question: "9000", answer: "nueve mil"},
  {question: "10000", answer: "diez mil"},
  {question: "100000", answer: "cien mil"},
  {question: "1000000", answer: "un millón"},
  {question: "1000000000", answer: "mil millones"},
  {question: "1000000000000", answer: "un billón"}
];

export const times = [
  {question: "1:00", answer: "es la una"},
  {question: "1:15", answer: "es la una y cuarto/es la una y quince"},
  {question: "1:30", answer: "es la una y media"},
  {question: "1:45", answer: "es la una menos cuarto/ es la una y cuarenta y cuatro"},
  {question: "2:00", answer: "son las dos"},
  {question: "2:15", answer: "son las dos y cuarto/son las dos  y quince"},
  {question: "2:30", answer: "son las dos y media"},
  {question: "2:45", answer: "son las tres menos cuarto/ son las dos y cuarenta y cuatro"},
  {question: "3:00", answer: "son las tres"},
  {question: "3:15", answer: "son las tres y cuarto/son las tres  y quince"},
  {question: "3:30", answer: "son las tres y media"},
  {question: "3:45", answer: "son las cuatro menos cuarto/ son las tres y cuarenta y cuatro"},
  {question: "4:00", answer: "son las cuatro"},
  {question: "4:15", answer: "son las cuatro y cuarto/son las cuatro  y quince"},
  {question: "4:30", answer: "son las cuatro y media"},
  {question: "4:45", answer: "son las cinco menos cuarto/ son las cuatro y cuarenta y cuatro"},
  {question: "5:00", answer: "son las cinco"},
  {question: "5:15", answer: "son las cinco y cuarto/son las cinco  y quince"},
  {question: "5:30", answer: "son las cinco y media"},
  {question: "5:45", answer: "son las seis menos cuarto/ son las cinco y cuarenta y cuatro"},
  {question: "6:00", answer: "son las seis"},
  {question: "6:15", answer: "son las seis y cuarto/son las seis  y quince"},
  {question: "6:30", answer: "son las seis y media"},
  {question: "6:45", answer: "son las siete menos cuarto/ son las seis y cuarenta y cuatro"},
  {question: "7:00", answer: "son las siete"},
  {question: "7:15", answer: "son las siete y cuarto/son las siete  y quince"},
  {question: "7:30", answer: "son las siete y media"},
  {question: "7:45", answer: "son las ocho menos cuarto/ son las siete y cuarenta y cuatro"},
  {question: "8:00", answer: "son las ocho"},
  {question: "8:15", answer: "son las ocho y cuarto/son las ocho  y quince"},
  {question: "8:30", answer: "son las ocho y media "},
  {question: "8:45", answer: "son las nueve menos cuarto/ son las ocho y cuarenta y cuatro"},
  {question: "9:00", answer: "son las nueve"},
  {question: "9:15", answer: "son las nueve y cuarto/son las nueve  y quince"},
  {question: "9:30", answer: "son las nueve y media"},
  {question: "9:45", answer: "son las diez menos cuarto/ son las nueve y cuarenta y cuatro"},
  {question: "10:00", answer: "son las diez"},
  {question: "10:15", answer: "son las diez y cuarto/son las diez  y quince"},
  {question: "10:30", answer: "son las diez y media"},
  {question: "10:45", answer: "son las once menos cuarto/ son las diez y cuarenta y cuatro"},
  {question: "11:00", answer: "son las once"},
  {question: "11:15", answer: "son las once y cuarto/son las once  y quince"},
  {question: "11:30", answer: "son las once y media"},
  {question: "11:45", answer: "son las doce menos cuarto/ son las once y cuarenta y cuatro"},
  {question: "12:00", answer: "son las doce"},
  {question: "12:15", answer: "son las doce y cuarto/son las doce  y quince"},
  {question: "12:30", answer: "son las doce y media "},
  {question: "12:45", answer: "es la una menos cuarto/ son las doce y cuarenta y cuatro"}
];

export const onePiece = [
  {question: "titere", answer: "puppet"},
  {question: "chiquillo", answer: "brat"},
  {question: "insolente", answer: "cheeky"},
  {question: "atravesare", answer: "I'll pierce through"},
  {question: "gusano", answer: "worm"},
  {question: "será idiota", answer: "what an idiot"},
  {question: "desgraciado", answer: "wretched/scoundrel"},
  {question: "no tiene caso", answer: "no point"},
  {question: "no puedes ni quedarte quieto", answer: "you can't even stay still"},
  {question: "como sea", answer: "anyhow"},
  {question: "agotaran", answer: "exhausted"},
  {question: "despertar", answer: "awake"},
  {question: "decepcionara", answer: "will disappoint"},
  {question: "ronquidos", answer: "snoring"},
  {question: "despedida", answer: "farewell"},
  {question: "el canal", answer: "carcass"},
  {question: "fastidies", answer: "bother/bug"},
  {question: "enroscadas", answer: "coiled"},
  {question: "malcriado", answer: "spoiled"},
  {question: "no se lo habia dicho", answer: "i hadn't told you"},
  {question: "recorrer", answer: "runs along"},
  {question: "reverie", answer: "daydream"},
  {question: "mesada", answer: "allowance"},
  {question: "solo estabamos jugando a los pirates", answer: "we were just playing pirates"},
  {question: "mas valor que huyan", answer: "its better to run"},
  {question: "Estaré allí en cuanto comience el horario de atención.", answer: "I will be there as soon as business hours begin."},
  {question: "habriamos podido reconstruirlos", answer: "we would have been able to rebuild them"},
  {question: "que envidia", answer: "how envious"},
  {question: "deberiamos atarla", answer: "we should tie it"},
  {question: "que va", answer: "that goes/hows it going"},
  {question: "estoy decidida", answer: "I am determined"},
  {question: "que encomiable", answer: "how commendable"},
  {question: "no puedo quitarselo", answer: "I can't take it off"},
  {question: "son ustedes", answer: "its you"},
  {question: "los viveres que ordenaron estan listos", answer: "the groceries you ordered are ready"},
  {question: "regresen", answer: "turn back"},
  {question: "desprende jugo", answer: "gives off juice [emit]"},
  {question: "no es dañino", answer: "is not harmful"},
  {question: "viste a un conocido", answer: "you saw an acquaintance"},
  {question: "su caparazon", answer: "its shell"},
  {question: "lo peor esta por venir", answer: "the worst is yet to come"},
  {question: "no pude lucirme", answer: "I couldn't show off"},
  {question: "sea comestible", answer: "is edible"},
  {question: "desatender", answer: "disregard"},
  {question: "arrebataron", answer: "snatched"},
  {question: "no se derrite", answer: "does not melt"},
  {question: "que fastidio", answer: "what a drag"},
  {question: "derretiremos el jarabe de almidon", answer: "let's melt the starch syrup"},
  {question: "habra problemas si despiertan", answer: "there'll be trouble if they wake up"},
  {question: "asi es", answer: "thats right"},
  {question: "era ingenuo", answer: "I was naive"},
  {question: "terminé siendo buscado ", answer: "ended up being searched for"},
  {question: "fui vencido aqui", answer: "I was defeated here"},
  {question: "rara vez hablo de eso", answer: "I rarely talk about it"},
  {question: "aun asi vuelves", answer: "you still come back"},
  {question: "aunque nos hayan salvado", answer: "even though you've saved us"},
  {question: "nadie mas que", answer: "no one else but"},
  {question: "falta mucho para eso ", answer: "a long way off"},
  {question: "ademas a recuperar a sanji", answer: "also to get sanji back"},
  {question: "asegúrense de proteger a sanji ", answer: "make sure you protect sanji "},
  {question: "te lo encargo", answer: "i'll leave you in charge"},
  {question: "seductor", answer: "seductive"},
  {question: "cascadas de jugo", answer: "juice waterfalls"},
  {question: "las agujas", answer: "the needles"},
  {question: "el jinete de grullas", answer: "the crane rider"},
  {question: "debilucho", answer: "wimpy"},
  {question: "corte lazo con mi familia", answer: "i cut ties with my family"},
  {question: "esquivenlo", answer: "dodge it"},
  {question: "sevira de marcador", answer: "serve as a marker"},
  {question: "paletas", answer: "lollipops"},
  {question: "cocodrilo parlante", answer: "talking crocodile"},
  {question: "podremos salir", answer: "we will be able to leave"},
  {question: "me asustan", answer: "scare me"},
  {question: "despacio", answer: "slowly"},
  {question: "no habia camino en ningun momento", answer: "there was no road at any time"},
  {question: "cicatriz", answer: "cicatriz"},
  {question: "me dan ganas de", answer: "makes me want to"},
  {question: "un reino marinero", answer: "a sea kingdom"},
  {question: "que decepcion", answer: "what a disappointment"},
  {question: "recuperar", answer: "Recover/retrieve/get Back"},
  {question: "aun asi", answer: "Even So"},
  {question: "la ira", answer: "Anger/wrath"},
  {question: "el prestigio", answer: "Prestige"},
  {question: "huyen", answer: "Flee/run Away"},
  {question: "babosas", answer: "Slugs"},
  {question: "hundan", answer: "Sink"},
  {question: "envenenó", answer: "Poisoned"},
  {question: "dulzura", answer: "Sweetness"},
  {question: "tapenlo", answer: "Cover It"},
  {question: "se saldra de la olla ", answer: "Will Come Out of the Pot"},
  {question: "cinco para las seis", answer: "5 Min to Six"},
  {question: "saludo de fuego", answer: "Fire Salute"},
  {question: "escudo", answer: "Shield"},
  {question: "saltemos", answer: "Were Jumping"},
  {question: "malagradecida", answer: "Ungrateful"},
  {question: "cenizas", answer: "Ashes"},
  {question: "despiadado", answer: "Ruthless/merciless/cruel"},
  {question: "imprudente", answer: "Wreckless"},
  {question: "menos mal", answer: "Luckily/thank Goodness"},
  {question: "venguen mi muerte", answer: "Avenge My Death"},
  {question: "eres muy blando", answer: "You Are Too Soft"},
  {question: "no lastimes", answer: "Don't Hurt [her]"},
  {question: "su vela", answer: "Your Sail"},
  {question: "nunca mas surcará el mar", answer: "Will Never Sail the Sea Again"},
  {question: "estrellarse", answer: "Crash"},
  {question: "anfibio", answer: "Amphibian"},
  {question: "las paletas se hicieron orugas", answer: "The Paddles Became Tracks"},
  {question: "desgraciado", answer: "Wretch/scoundrel"},
  {question: "cubierta", answer: "Deck"},
  {question: "se agota", answer: "Depleted/run Out/exhausted"},
  {question: "mas fuerte se hara", answer: "The Stronger it Will Become"},
  {question: "se hace mas fuerte en la batalla", answer: "It Becomes Stronger in Battle"},
  {question: "tonterias", answer: "Foolishness/nonsense"},
  {question: "no hay marcha atras", answer: "There's No Turning Back "},
  {question: "batalla de huida", answer: "Battle of Flight"},
  {question: "un miron", answer: "?"},
  {question: "que desperdicio", answer: "What a Waste"},
  {question: "se hirvieron", answer: "Boiled"},
  {question: "nos herviremos despues", answer: "We Will Be Boiled Afterwards"},
  {question: "ardiendo", answer: "Burning"},
  {question: "no saciara a big mom", answer: "Will Not Satisfy Big Mom"},
  {question: "hijastro", answer: "Stepson"},
  {question: "disminuye", answer: "Decreases/subside"},
  {question: "retraigan", answer: "Retract"},
  {question: "nieto mio cuyo", answer: "My Grandson Whose"},
  {question: "diste a luz ", answer: "You Gave Birth"},
  {question: "nadie se habria burlado", answer: "No One Would Have Made Fun of You"},
  {question: "acabamos de reunirnos ", answer: "We Just Met"},
  {question: "aunque hubieras huido", answer: "Even If You Had Fled"},
  {question: "heredando", answer: "Inheriting"},
  {question: "adopta", answer: "Adopt/embrace"},
  {question: "rogar unirtenos", answer: "Beg to Join Us"},
  {question: "elegiste vencerme", answer: "You Chose to Defeat Me"},
  {question: "conque el", answer: "With The"},
  {question: "retaguardia", answer: "Rearguard"},
  {question: "nava insignia", answer: "Flagship"},
  {question: "tartes", answer: "Tartes"},
  {question: "estribor", answer: "Starboard"},
  {question: "ostentosos", answer: "Ostentatious"},
  {question: "adelgazando", answer: "Slimming"},
  {question: "alcance ", answer: "Reach"},
  {question: "diria ahora", answer: "I Would Say Now"},
  {question: "cuerpo a cuerpo", answer: "Melee to Melee"},
  {question: "la derribaré", answer: "I'll Take Her Down"},
  {question: "que astuto", answer: "How Crafty"},
  {question: "un par de cosas", answer: "A Couple of Things"},
  {question: "adonde apuntas ", answer: "Where You Aim"},
  {question: "los agotara con una sola noche", answer: "Will Exhaust Them in a Single Night"},
  {question: "les dejeremos la seguridad de la ruta", answer: "We'll Leave Them the Safety of the Road"},
  {question: "soportar ", answer: "Endure"},
  {question: "endureces", answer: "Harden"},
  {question: "desatar", answer: "Untie"},
  {question: "por que no le doy", answer: "Why Don't I Give You"},
  {question: "dirige", answer: "Direct"},
  {question: "alboroto", answer: "Fuss"},
  {question: "solo lo superare", answer: "I'll Just Get Over It"},
  {question: "despedazará", answer: "It Will Tear Apart"},
  {question: "que decepcion", answer: "what a disappointment"}
];

export const dates = [
  {question: "32726", answer: "seis de agosto de mil novecientos ochenta y nueve"},
  {question: "44852", answer: "deciocho de octubre de dos mil veintidos "},
  {question: "-9981", answer: "uno de septiembre de mil ochocientos setenta y dos"},
  {question: "17964", answer: "siete de marzo de mil novecientos cuarenta y nueve"},
  {question: "37610", answer: "veinte de diciembre de dos mill dos "},
  {question: "42894", answer: "ocho de junio de dos mil decisiete"},
  {question: "40298", answer: "treinta de abril de dos mil diez"},
  {question: "37662", answer: "diez de febrero de dos mil tres"},
  {question: "26569", answer: "veintisiete de septiembre de mil novecientos setenta y dos"},
  {question: "44024", answer: "doce de julio de dos mil veinte"}
];

export 

const colors = [
  {question: "red", answer: "aka"},
  {question: "green", answer: "midori"},
  {question: "blue", answer: "ao"},
  {question: "light", answer: "akarui"},
  {question: "dark", answer: "kurai"},
  {question: "yellow", answer: "ki"},
  {question: "brown", answer: "buraun"},
  {question: "pink", answer: "pinku"},
  {question: "orange", answer: "orenji"},
  {question: "black", answer: "burakku"},
  {question: "white", answer: "shiro"},
  {question: "gray", answer: "gure"},
  {question: "color", answer: "kara"}
];

const people = [
  {question: "son", answer: "musuko"},
  {question: "daughter", answer: "musume"},
  {question: "mother", answer: "haha"},
  {question: "father", answer: "chichi"},
  {question: "parent", answer: "oya"},
  {question: "baby", answer: "akachan"},
  {question: "man", answer: "otoko"},
  {question: "woman", answer: "onna"},
  {question: "brother", answer: "nissan"},
  {question: "sister", answer: "imouto"},
  {question: "family", answer: "kazoku"},
  {question: "grandfather", answer: "jiisan"},
  {question: "grandmother", answer: "obaasan"},
  {question: "husband", answer: "otto"},
  {question: "wife", answer: "tsuma"},
  {question: "king", answer: "ousama"},
  {question: "queen", answer: "jouu"},
  {question: "president", answer: "daitouryou"},
  {question: "neighbor", answer: "rinjin"},
  {question: "boy", answer: "otokonoko"},
  {question: "girl", answer: "onnanoko"},
  {question: "child", answer: "kodomo"},
  {question: "adult", answer: "otona"},
  {question: "human", answer: "ningen"},
  {question: "friend", answer: "yuujin"},
  {question: "victim", answer: "higaisha"},
  {question: "player", answer: "pureiya"},
  {question: "fan", answer: "fan"},
  {question: "crowd", answer: "gunshuu"},
  {question: "person", answer: "jin"}
];

const job = [
  {question: "Teacher", answer: "sensei"},
  {question: "student", answer: "gakusei"},
  {question: "lawyer", answer: "bengoshi"},
  {question: "doctor", answer: "isha"},
  {question: "patient", answer: "kanja"},
  {question: "waiter", answer: "weita"},
  {question: "secretary", answer: "hisho"},
  {question: "priest", answer: "shinpu"},
  {question: "police", answer: "keisatsu"},
  {question: "army", answer: "guntai"},
  {question: "soldier", answer: "heishi"},
  {question: "artist", answer: "gaka"},
  {question: "author", answer: "sakka"},
  {question: "manager", answer: "shachou"},
  {question: "reporter", answer: "kisha"},
  {question: "actor", answer: "haiyuu"},
  {question: "job", answer: "shoku"}
];

const society = [
  {question: "hell", answer: "jigoku"},
  {question: "death", answer: "shi"},
  {question: "medicine", answer: "igaku"},
  {question: "money", answer: "okane"},
  {question: "dollar", answer: "doru"},
  {question: "bill", answer: "seikyuusho"},
  {question: "marriage*", answer: "konin"},
  {question: "wedding*", answer: "kekkonshiki"},
  {question: "team", answer: "chimu"},
  {question: "relationship", answer: "kankei"},
  {question: "race (ethnicity)", answer: "jinshu"},
  {question: "sex (the act)", answer: "sekkusu"},
  {question: "sex (gender)", answer: "sei"},
  {question: "murder", answer: "satsujin"},
  {question: "prison", answer: "keimusho"},
  {question: "technology", answer: "tekunoroji"},
  {question: "energy", answer: "enerugi"},
  {question: "war", answer: "Senso"},
  {question: "peace", answer: "heiwa"},
  {question: "attack", answer: "kogeki"},
  {question: "election", answer: "senkyo"},
  {question: "magazine", answer: "zasshi"},
  {question: "newspaper", answer: "shinbun"},
  {question: "poison", answer: "doku"},
  {question: "gun", answer: "ju"},
  {question: "sport", answer: "supotsu"},
  {question: "race (sport)", answer: "kyousou"},
  {question: "exercise", answer: "undo"},
  {question: "ball", answer: "boru"},
  {question: "game", answer: "gemu"},
  {question: "price", answer: "kakaku"},
  {question: "contract", answer: "keiyaku"},
  {question: "drug", answer: "kusuri"},
  {question: "sign", answer: "sain"},
  {question: "science", answer: "Saiensu"},
  {question: "God", answer: "kami"}
];

const art = [
  {question: "band", answer: "bando"},
  {question: "song", answer: "uta"},
  {question: "instrument (musical)", answer: "gakki"},
  {question: "music", answer: "Ongaku"},
  {question: "movie", answer: "eiga"},
  {question: "art", answer: "geijutsu"}
];

const beverages = [
  {question: "coffee", answer: "kohi"},
  {question: "tea", answer: "cha"},
  {question: "wine", answer: "wain"},
  {question: "beer", answer: "biru"},
  {question: "juice", answer: "jusu"},
  {question: "water", answer: "mizu"},
  {question: "milk", answer: "gyuunyuu"},
  {question: "beverage", answer: "inryou"}
];

const food = [
  {question: "egg", answer: "tamago"},
  {question: "cheese", answer: "chizu"},
  {question: "bread", answer: "pan"},
  {question: "soup", answer: "supu"},
  {question: "cake", answer: "keki"},
  {question: "chicken", answer: "keiniku"},
  {question: "pork", answer: "butaniku"},
  {question: "beef", answer: "gyuuniku"},
  {question: "apple", answer: "ringo"},
  {question: "banana", answer: "banana"},
  {question: "orange", answer: "orenji"},
  {question: "lemon", answer: "remon"},
  {question: "corn", answer: "kon"},
  {question: "rice", answer: "kome"},
  {question: "oil", answer: "abura"},
  {question: "seed", answer: "tane"},
  {question: "knife", answer: "naifu"},
  {question: "spoon", answer: "supun"},
  {question: "fork", answer: "foku"},
  {question: "plate", answer: "sara"},
  {question: "cup", answer: "kappu"},
  {question: "breakfast", answer: "asa"},
  {question: "lunch", answer: "hiru"},
  {question: "dinner", answer: "yoru"},
  {question: "sugar", answer: "satou"},
  {question: "salt", answer: "shio"},
  {question: "bottle", answer: "botoru"},
  {question: "food", answer: "tabemono"}
];

const home = [
  {question: "table", answer: "teburu"},
  {question: "chair", answer: "isu"},
  {question: "bed", answer: "beddo"},
  {question: "dream", answer: "yume"},
  {question: "window", answer: "mado"},
  {question: "door", answer: "kuchi"},
  {question: "bedroom", answer: "shinshitsu"},
  {question: "kitchen", answer: "daidokoro"},
  {question: "bathroom", answer: "furo"},
  {question: "pencil", answer: "enpitsu"},
  {question: "pen", answer: "pen"},
  {question: "photograph", answer: "shashin"},
  {question: "soap", answer: "sekken"},
  {question: "book", answer: "hon"},
  {question: "page", answer: "peji"},
  {question: "key", answer: "ki"},
  {question: "paint", answer: "peinto"},
  {question: "letter", answer: "tegami"},
  {question: "note", answer: "noto"},
  {question: "wall", answer: "kabe"},
  {question: "paper", answer: "kami"},
  {question: "floor", answer: "furoa"},
  {question: "ceiling", answer: "tenjou"},
  {question: "roof", answer: "yane"},
  {question: "pool", answer: "puru"},
  {question: "lock", answer: "rokku"},
  {question: "telephone", answer: "denwa"},
  {question: "garden", answer: "niwa"},
  {question: "yard", answer: "niwa"},
  {question: "needle", answer: "hari"},
  {question: "bag", answer: "kaban"},
  {question: "box", answer: "hako"},
  {question: "gift", answer: "gifuto"},
  {question: "card", answer: "kado"},
  {question: "ring", answer: "ringu"},
  {question: "tool", answer: "tsuru"}
];

const electronics = [
  {question: "clock", answer: "tokei"},
  {question: "lamp", answer: "ranpu"},
  {question: "fan", answer: "senpuuki"},
  {question: "cell phone", answer: "keitaidenwa"},
  {question: "network", answer: "nettowaku"},
  {question: "computer ", answer: "konpyuta"},
  {question: "program", answer: "kodo"},
  {question: "laptop", answer: "notopasokan"},
  {question: "screen", answer: "sukurin"},
  {question: "camera", answer: "kamera"},
  {question: "television", answer: "terebi"},
  {question: "radio", answer: "rajio"}
];

const nature = [
  {question: "sea", answer: "umi"},
  {question: "ocean", answer: "umi"},
  {question: "river", answer: "kawa"},
  {question: "mountain", answer: "yama"},
  {question: "rain", answer: "ame"},
  {question: "snow", answer: "yuki"},
  {question: "tree", answer: "ki"},
  {question: "sun", answer: "taiyou"},
  {question: "moon", answer: "tsuki"},
  {question: "world", answer: "sekai"},
  {question: "Earth", answer: "chikyuu"},
  {question: "forest", answer: "mori"},
  {question: "sky", answer: "kara"},
  {question: "plant", answer: "shokubutsu"},
  {question: "wind", answer: "kaze"},
  {question: "soil/earth", answer: "tsuchi"},
  {question: "flower", answer: "hana"},
  {question: "valley", answer: "tani"},
  {question: "root", answer: "ne"},
  {question: "lake", answer: "mizumi"},
  {question: "star", answer: "hoshi"},
  {question: "grass", answer: "kusa"},
  {question: "leaf", answer: "ha"},
  {question: "air", answer: "kuuki"},
  {question: "sand", answer: "suna"},
  {question: "beach", answer: "hamabe"},
  {question: "wave", answer: "nami"},
  {question: "fire", answer: "hi"},
  {question: "ice", answer: "koori"},
  {question: "island", answer: "shima"},
  {question: "hill", answer: "oka"},
  {question: "heat", answer: "netsu"},
  {question: "nature", answer: "shizen"}
];

const materials = [
  {question: "glass,", answer: "garasu"},
  {question: "metal,", answer: "kinzoku"},
  {question: "plastic,", answer: "purasuchikku"},
  {question: "wood,", answer: "ki"},
  {question: "stone,", answer: "ishi"},
  {question: "diamond,", answer: "daiyamondo"},
  {question: "clay,", answer: "nendo"},
  {question: "dust,", answer: "dasuto"},
  {question: "gold,", answer: "kane"},
  {question: "copper,", answer: "dou"},
  {question: "silver,", answer: "gin"},
  {question: "material", answer: "zairyou"}
];
const math = [
  {question: "meter", answer: "metoru"},
  {question: "centimeter", answer: "senchime toru"},
  {question: "kilogram", answer: "kiroguramu"},
  {question: "inch", answer: "inchi"},
  {question: "foot", answer: "fito"},
  {question: "pound", answer: "pondo"},
  {question: "half", answer: "hafu"},
  {question: "circle", answer: "en"},
  {question: "square", answer: "seihoukei"},
  {question: "temperature", answer: "ondo"},
  {question: "date", answer: "hiduke"},
  {question: "weight", answer: "juuryou"},
  {question: "edge", answer: "ejji"},
  {question: "corner", answer: "kona"}
];

const nouns = [
  {question: "map", answer: "chizu"},
  {question: "dot", answer: "ten"},
  {question: "consonant", answer: "shiin"},
  {question: "vowel", answer: "boin"},
  {question: "light", answer: "raito"},
  {question: "sound", answer: "oto"},
  {question: "yes", answer: "hai"},
  {question: "no", answer: "ie"},
  {question: "piece", answer: "pisu"},
  {question: "pain", answer: "itami"},
  {question: "injury", answer: "kizu"},
  {question: "hole", answer: "ana"},
  {question: "image", answer: "imeji"},
  {question: "pattern", answer: "patan"},
  {question: "noun", answer: "meishi"},
  {question: "verb", answer: "doushi"},
  {question: "adjective", answer: "keiyoushi"}
];

const directions = [
  {question: "top", answer: "toppu"},
  {question: "bottom", answer: "teiman"},
  {question: "side", answer: "sokumen"},
  {question: "front", answer: "mae"},
  {question: "back", answer: "haimen"},
  {question: "outside", answer: "sotogawa"},
  {question: "inside", answer: "uchigawa"},
  {question: "up", answer: "ue"},
  {question: "down", answer: "moto"},
  {question: "left", answer: "hidari"},
  {question: "right", answer: "migi"},
  {question: "straight", answer: "massugu"},
  {question: "north", answer: "kita"},
  {question: "south", answer: "minami"},
  {question: "east", answer: "higashi"},
  {question: "west", answer: "nishi"},
  {question: "direction", answer: "houkou"}
];

const seasons = [
  {question: "Spring", answer: "haru"},
  {question: "Winter", answer: "fuyu"},
  {question: "Fall", answer: "aki"},
  {question: "season", answer: "kisetsu"}
];


const months = [
  {question: "January", answer: "ichigatsu"},
  {question: "February", answer: "nigatsu"},
  {question: "March", answer: "sangatsu"},
  {question: "April", answer: "shigatsu"},
  {question: "May", answer: "gogatsu"},
  {question: "June", answer: "rokugatsu"},
  {question: "July", answer: "shichigatsu"},
  {question: "August", answer: "hachigatsu"},
  {question: "September", answer: "kugatsu"},
  {question: "October", answer: "juugatsu"},
  {question: "November", answer: "juuichigatsu"},
  {question: "December", answer: "juunigatsu"}
];

const days = [
  {question: "Monday", answer: "getsuyoubi"},
  {question: "Tuesday", answer: "kayoubi"},
  {question: "Wednesday", answer: "suiyoubi"},
  {question: "Thursday", answer: "mokuyoubi"},
  {question: "Friday", answer: "kinyoubi"},
  {question: "Saturday", answer: "doyou"},
  {question: "Sunday", answer: "nichiyoubi"}
];

const verbs = [
  {question: "to work", answer: "hataraku"},
  {question: "to play", answer: "asobu"},
  {question: "to walk", answer: "aruka"},
  {question: "to run", answer: "hashiru"},
  {question: "to drive", answer: "doraibu"},
  {question: "to fly", answer: "ageru"},
  {question: "to swim", answer: "oyogu"},
  {question: "to go", answer: "iku"},
  {question: "to stop", answer: "tomaru"},
  {question: "to follow", answer: "tadoru"},
  {question: "to think", answer: "kangaeru"},
  {question: "to speak/say", answer: "iu"},
  {question: "to eat", answer: "taberu"},
  {question: "to drink", answer: "nomu"},
  {question: "to kill", answer: "korosu"},
  {question: "to die", answer: "shinu"},
  {question: "to smile", answer: "hohoemu"},
  {question: "to laugh", answer: "warau"},
  {question: "to cry", answer: "naku"},
  {question: "to buy", answer: "kau"},
  {question: "to pay", answer: "shiharau"},
  {question: "to sell", answer: "uru"},
  {question: "to shoot", answer: "utsu"},
  {question: "to learn", answer: "narau"},
  {question: "to jump", answer: "tobinoku"},
  {question: "to smell", answer: "niou"},
  {question: "to hear", answer: "kiku"},
  {question: "to listen*", answer: "kiku"},
  {question: "to taste", answer: "ajiwau"},
  {question: "to touch", answer: "sawaru"},
  {question: "to see", answer: "miru"},
  {question: "to watch(TV)", answer: "miru"},
  {question: "to kiss", answer: "suu"},
  {question: "to burn", answer: "yaku"},
  {question: "to melt", answer: "toku"},
  {question: "to dig", answer: "horu"},
  {question: "to explode", answer: "hiwofuku"},
  {question: "to sit", answer: "suwaru"},
  {question: "to stand", answer: "tatsu"},
  {question: "to love", answer: "aisuru"},
  {question: "to pass by", answer: "sugiru"},
  {question: "to cut", answer: "kiru"},
  {question: "to fight", answer: "momu"},
  {question: "to lie down", answer: "neru"},
  {question: "to dance", answer: "odoru"},
  {question: "to sleep", answer: "nemuru"},
  {question: "to wake up", answer: "mezameru"},
  {question: "to sing", answer: "utua"},
  {question: "to count", answer: "kazoeru"},
  {question: "to marry", answer: "totsugu"},
  {question: "to pray", answer: "inoru"},
  {question: "to win", answer: "katsu"},
  {question: "to lose", answer: "ushinau"},
  {question: "to mix/stir", answer: "mazeru"},
  {question: "to bend", answer: "magaru"},
  {question: "to wash", answer: "arau"},
  {question: "to cook", answer: "taku"},
  {question: "to open", answer: "hiraku"},
  {question: "to close", answer: "shimeru"},
  {question: "to write", answer: "kaku"},
  {question: "to call", answer: "yobu"},
  {question: "to turn", answer: "magaru"},
  {question: "to build", answer: "tateru"},
  {question: "to teach", answer: "oshieru"},
  {question: "to grow", answer: "nobiru"},
  {question: "to draw", answer: "egaku"},
  {question: "to feed", answer: "kuwasu"},
  {question: "to catch", answer: "toru"},
  {question: "to throw", answer: "nageru"},
  {question: "to clean", answer: "haku"},
  {question: "to fall", answer: "taoreru"},
  {question: "to push", answer: "osu"},
  {question: "to pull", answer: "hipparu"},
  {question: "to carry", answer: "hakobu"},
  {question: "to break", answer: "oru"},
  {question: "to wear", answer: "kiru"},
  {question: "to hang", answer: "tsurusu"},
  {question: "to shake", answer: "yureru"},
  {question: "to sign", answer: "shosuru"},
  {question: "to beat", answer: "yattsukeru"},
  {question: "to lift", answer: "takameru"},
  {question: "to find", answer: "mitsukeru"}
];

const adjectives = [

];

const pronouns = [
  {question: "I", answer: "watashi"},
  {question: "you (singular)", answer: "anata"},
  {question: "he", answer: "kare"},
  {question: "she", answer: "kanojo"},
  {question: "it", answer: "sore"},
  {question: "we", answer: "watashitachi"},
  {question: "you (plural)", answer: "Anata-tatchi "},
  {question: "they", answer: "karera"}
];
